src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecipeRepository::class)
 */
class Recipe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $time_prepare;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $time_cooking;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $time_rest;

    /**
     * @ORM\Column(type="array")
     */
    private $ingredients = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $tools = [];

    /**
     * @ORM\Column(type="array")
     */
    private $steps = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $id_author;

    /**
     * @ORM\Column(type="time")
     */
    private $created_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imageFilename;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTimePrepare(): ?string
    {
        return $this->time_prepare;
    }

    public function setTimePrepare(string $time_prepare): self
    {
        $this->time_prepare = $time_prepare;

        return $this;
    }

    public function getTimeCooking(): ?string
    {
        return $this->time_cooking;
    }

    public function setTimeCooking(string $time_cooking): self
    {
        $this->time_cooking = $time_cooking;

        return $this;
    }

    public function getTimeRest(): ?string
    {
        return $this->time_rest;
    }

    public function setTimeRest(?string $time_rest): self
    {
        $this->time_rest = $time_rest;

        return $this;
    }

    public function getIngredients(): ?array
    {
        return $this->ingredients;
    }

    public function setIngredients(array $ingredients): self
    {
        $this->ingredients = $ingredients;

        return $this;
    }

    public function getTools(): ?array
    {
        return $this->tools;
    }

    public function setTools(?array $tools): self
    {
        $this->tools = $tools;

        return $this;
    }

    public function getSteps(): ?array
    {
        return $this->steps;
    }

    public function setSteps(array $steps): self
    {
        $this->steps = $steps;

        return $this;
    }

    public function getIdAuthor(): ?int
    {
        return $this->id_author;
    }

    public function setIdAuthor(int $id_author): self
    {
        $this->id_author = $id_author;

        return $this;
    }

    public function getCreatedTime(): ?\DateTimeInterface
    {
        return $this->created_time;
    }

    public function setCreatedTime(\DateTimeInterface $created_time): self
    {
        $this->created_time = $created_time;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('time_prepare')
            ->add('time_cooking')
            ->add('imageFilename', FileType::class, [
                'label' => 'Image',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '2048k',
                        'mimeTypes' => [
                            'image/*'
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image',
                    ])
                ],
            ])
            ->add('time_rest')
            ->add('ingredients')
            ->add('tools')
            ->add('steps')
            ->add('id_author')
            ->add('created_time')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use App\Form\RecipeType;
use App\Repository\RecipeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/recipe")
 */
class RecipeController extends AbstractController
{
    /**
     * @Route("/", name="recipe_index", methods={"GET"})
     */
    public function index(RecipeRepository $recipeRepository): Response
    {
        return $this->render('recipe/index.html.twig', [
            'recipes' => $recipeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="recipe_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $recipe = new Recipe();
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recipe);
            $entityManager->flush();

            return $this->redirectToRoute('recipe_index');
        }

        return $this->render('recipe/new.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="recipe_show", methods={"GET"})
     */
    public function show(Recipe $recipe): Response
    {
        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="recipe_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Recipe $recipe): Response
    {
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('recipe_index');
        }

        return $this->render('recipe/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="recipe_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Recipe $recipe): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($recipe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('recipe_index');
    }
}

templates/recipe/_delete_form.html.twig
<form method="post" action="{{ path('recipe_delete', {'id': recipe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recipe/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recipe{% endblock %}

{% block body %}
    <h1>Edit Recipe</h1>

    {{ include('recipe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('recipe_index') }}">back to list</a>

    {{ include('recipe/_delete_form.html.twig') }}
{% endblock %}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe index{% endblock %}

{% block body %}
    <div class="container" class="pt-10">
        <h1>Recettes</h1>

        <a href="{{ path('recipe_new') }}">Créer une recette</a>

            {% for recipe in recipes %}
                <div class="card" id="{{ recipe.id }}" style="width: 18rem;">
                    <img src="..." class="card-img-top" alt="{{ recipe.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.name }}</h5>
                        <i>Créé le {{ recipe.createdTime ? recipe.createdTime|date('H:i:s') : '' }}</i>
                        <p class="card-text">{{ recipe.description }}</p>
                        <a href="{{ path('recipe_show', {'id': recipe.id}) }}" class="btn btn-primary">Voir</a>
                    </div>
                </div>
            {% else %}
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Aucune recette disponible</h5>
                    </div>
                </div>
            {% endfor %}


    </div>
{% endblock %}

templates/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recipe{% endblock %}

{% block body %}
    <h1>Create new Recipe</h1>

    {{ include('recipe/_form.html.twig') }}

    <a href="{{ path('recipe_index') }}">back to list</a>
{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe{% endblock %}

{% block body %}
    <h1>Recipe</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ recipe.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ recipe.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ recipe.description }}</td>
            </tr>
            <tr>
                <th>Time_prepare</th>
                <td>{{ recipe.timePrepare }}</td>
            </tr>
            <tr>
                <th>Time_cooking</th>
                <td>{{ recipe.timeCooking }}</td>
            </tr>
            <tr>
                <th>Time_rest</th>
                <td>{{ recipe.timeRest }}</td>
            </tr>
            <tr>
                <th>Ingredients</th>
                <td>{{ recipe.ingredients ? recipe.ingredients|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Tools</th>
                <td>{{ recipe.tools ? recipe.tools|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Steps</th>
                <td>{{ recipe.steps ? recipe.steps|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Id_author</th>
                <td>{{ recipe.idAuthor }}</td>
            </tr>
            <tr>
                <th>Created_time</th>
                <td>{{ recipe.createdTime ? recipe.createdTime|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('recipe_index') }}">back to list</a>

    <a href="{{ path('recipe_edit', {'id': recipe.id}) }}">edit</a>

    {{ include('recipe/_delete_form.html.twig') }}
{% endblock %}